server.port=8761
spring.application.name=naming-server

#spring.profiles.active=dev
#spring.cloud.config.profile=dev

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoint.gateway.access=unrestricted
management.endpoints.web.exposure.include=*

management.tracing.sampling.probability=1.0
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs

logging.level.root=INFO
#logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]
